config/routes.rb
Vicetracker::Application.routes.draw do
  
  devise_for :users

  resources :users, only: [:show, :edit, :update, :destroy]

  resources :vices do
    resources :subvices, shallow: true do
      resources :purchases, shallow: true
    end
  end

  resources :inquiries, :only => [:new, :create] do
    get 'thank_you', :on => :collection
  end

  get 'pages/home'
  get 'pages/about'
  get 'pages/contact'

  authenticated :user do
    root :to => 'vices#index', :as => "authenticated_root"
  end
 
  root :to => 'pages#home'
end

app/views/shared/_header.html.erb
<div class="container">
  <div class="navbar-wrapper navbar-default navbar-fixed-top" role="navigation">
    <div class="container">

      <div class="navbar-header">
        <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
          <span class="sr-only">Toggle navigation</span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <%= link_to 'VICE TRACKER', "/", :class => "navbar-brand" %>
      </div>

      <div class="navbar-collapse collapse">
        <ul class="nav navbar-nav">
          <li><%= link_to 'About', pages_about_path %></li>
          <li><%= link_to 'Contact', new_inquiry_path %></li>
        </ul>
          <% if user_signed_in? %>
        <ul class="nav navbar-nav">
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown">Vices <b class="caret"></b></a>
            <ul class="dropdown-menu">
              <li><%= link_to 'Add a Vice', new_vice_path, :class => "add-vice" %></li>
                  <% current_user.vices.each do |v| %>
                    <li><%= link_to v.name, v %></li>
                  <% end %>
            </ul>
          </li>
        </ul>
        <ul class="nav navbar-nav navbar-right">
          <li class="dropdown">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown"><%= current_user.username %> <b class="caret"></b></a>
              <ul class="dropdown-menu">
                <li><%= link_to 'Edit Profile', edit_user_registration_path %></li>
                <li><%= link_to "Sign Out", destroy_user_session_path, :method => :delete %></li>
              </ul>
          <% else %>
              <ul class="nav navbar-nav navbar-right">
                <li><%= link_to "Sign Up", new_user_registration_path %></li>
                <li><%= link_to "Sign In", new_user_session_path %></li>
              </ul>
          <% end %>
            </li>
        </ul> 

      </div>

    </div>
    <div class="container">
      <span class="alert-notice"><%= notice %></span>
      <span class="alert-error"><%= alert %></span>
    </div>
  </div>

</div>