config/routes.rb
Vicetracker::Application.routes.draw do
  
  devise_for :users

  resources :users, only: [:show, :edit, :update, :destroy]

  resources :vices do
    resources :subvices, shallow: true do
      resources :purchases, shallow: true
    end
  end

  resources :inquiries, :only => [:new, :create] do
    get 'thank_you', :on => :collection
  end

  get 'pages/home'
  get 'pages/about'
  get 'pages/contact'

  authenticated :user do
    root :to => 'vices#index', :as => "authenticated_root"
  end
 
  root :to => 'pages#home'
end

app/models/vice.rb
class Vice < ActiveRecord::Base
    has_and_belongs_to_many :users
    has_many :subvices

    validates :name, presence: true

end

app/controllers/vices_controller.rb
class VicesController < ApplicationController
    before_action :set_vice, only: [:show, :destroy]

    def index
        @vices = current_user.vices
    end

    def new
        @vice = Vice.new
    end

    def show
        @subvices = current_user.subvices.where(vice: @vice)
    end

    def create
        @vice = Vice.find_by(id: params[:vice][:id])
        if current_user.vices.detect {|v| v["name"] == @vice.name } == nil
            current_user.vices << @vice
        else
            redirect_to new_vice_path, alert: 'Vice already exists.' and return
        end
        redirect_to vice_path(@vice), notice: 'Vice successfully created.'
    end

    def destroy
        current_user.vices.delete(@vice)
        redirect_to vices_path, notice: 'Vice successfully removed.'
    end

    private

    def set_vice
        @vice = current_user.vices.find(params[:id])
    end

end

app/views/vices/_form.html.erb
<div class="jumbotron new-vice">
    <%= form_for(@vice) do |f| %>
        <h1>New Vice</h1>
        
        <div class="field">
            <%= f.collection_select :id, Vice.all, :id, :name, :class => "form-control" %>
        </div>
        <div class="actions">
            <%= f.submit "Add Vice", :class => "btn btn-lg btn-primary" %>
        </div>
    <% end %>
</div>

app/views/vices/index.html.erb
<div class="container">
    <div class="jumbotron">
        <h1><%= current_user.username %>, your timeline</h1>
    </div>

    <div class="timeline">
        <div class="day">
            <div class="end"></div>
        </div>
        <% current_user.purchases.order("created_at DESC").group_by(&:group_by_criteria).each do |k,v| %>
        <div class="day">
            <div class="date">
                <span class="head"><%= k.to_time.strftime('%B %e') %></span>
            </div>
            <div class="marker">
            </div>
            <div class="circle-box">
                <span class="outer-circle"></span><span class="inner-circle"></span>
            </div>
            
            <div class="triangle-box">
                <span class="left-triangle"></span>
            </div>            
            <div class="purchases">
                <div class="box">
                    <% v.each do |x| %>
                        <div>
                            <%= x.quantity %> 
                            (<%= x.subvice.name %>) totalling 
                            $<%= x.cost %> 
                            <%= x.created_at.to_time.strftime('at %l:%M %p') %>
                        </div>
                    <% end %>
                </div>
            </div>
        </div>
        <% end %>
        
        <div class="day">
            <div class="large-circle"></div>
            <div class="joined">
                You joined <%= current_user.created_at.to_time.strftime('%B %e at %l:%M %p') %>
            </div>
        </div>
    </div>

</div>

app/views/vices/new.html.erb
<div class="container">
    <%= render 'form' %>
</div>

app/views/vices/show.html.erb
<div class="container">
    <div class="jumbotron">
        <div class="heading"><%= @vice.name %></div>
        <span><%= link_to 'Remove Vice', @vice, method: :delete, data: { confirm: 'Are you sure?' } %></span>
    </div>
    <div class="chart-heading">Amount consumed per day</div>
    <div>
        <%= column_chart @subvices.map{|subvice|
        {name: subvice.name, data: subvice.purchases.group_by_day(:created_at).sum(:quantity)}
        } %> 
    </div>
    
    <div class="add-subvice">
        <%= link_to 'Add Sub category', new_vice_subvice_path(@vice) %>
    </div>

    <% if @subvices.present? %>
        <% @subvices.each do |subvice| %>
            <div class="col-lg-4">
                <div class="subvice-box">
                    <div class="vice-name">
                        <%= subvice.name.capitalize %>
                    </div>
                    <div>
                        <%= distance_of_time_in_words(Time.now - current_user.last_time_consumed(subvice.id)) %> since you last drank <%= subvice.name %>
                    </div>
                    <% if current_user.goal_achieved(subvice, Time.now) %>
                        <div><span class="label label-success">You're on track to achieve daily goal</span></div>
                    <% else %>
                        <div><span class="label label-fail">You did not achieve daily goal</span></div>
                    <% end %>
                    <div class="subvice-modifiers">
                        <%= link_to 'Add Purchase', new_subvice_purchase_path(subvice) %>
                        <%= link_to 'Edit', edit_subvice_path(subvice) %> 
                        <%= link_to 'Remove', subvice, method: :delete, data: { confirm: 'Are you sure?' } %>
                    </div>
                    <div class="overlay"></div>
                    <div class="corner-overlay-content">+</div>
                </div>
                
            </div><!-- /.col-lg-4 -->
        <% end %>
    <% else %>
        <div class="subvice-box">
            <div class="row">
                <div class="column vice-name">You haven't added any subvices yet.</div>
            </div>
        </div>
    <% end %>
</div>